---
galaxy_info:
  role_name: arc_onboard
  author: sysadmin
  description: Wrapper role for Azure Arc onboarding using azure.azcollection.azure_arc
  license: MIT
  min_ansible_version: "2.16"
dependencies: []
