---
- name: Setup Apache server
  hosts: localhost
  become: true

  tasks:
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
      tags: i-httpd

    - name: Start apache2
      ansible.builtin.service:
        name: apache2
        state: started
      tags: s-httpd
